/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mice */

#ifndef _Included_Mice
#define _Included_Mice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mice
 * Method:    tryBuild
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Mice_tryBuild
  (JNIEnv *, jobject);

/*
 * Class:     Mice
 * Method:    pollEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mice_pollEvents
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
